In [9]:
import numpy as np


In [2]:
#1D array
d= np.array([1,2,3])
print(d)

[1 2 3]


In [28]:
#2D array
dd = np.array([[1,3,5,7],[2,4,6,8]])
print(dd)

[[1 3 5 7]
 [2 4 6 8]]


In [4]:
#get dimension
d.ndim
dd.ndim

2

In [29]:
#get shape
dd.shape

(2, 4)

In [6]:
dd = np.array([[1,3,5,7],[2,4,6,8]])
print(dd)
#ger a specific index
dd[1,3]


[[1 3 5 7]
 [2 4 6 8]]


8

In [30]:
dd = np.array([[1,3,5,7],[2,4,6,8]])
dd[0,0:3:2]

array([1, 5])

In [8]:
dd = np.array([[1,3,5,7],[2,4,6,8]])
dd[0,2]=6
print(dd)

[[1 3 6 7]
 [2 4 6 8]]


In [31]:
dd = np.array([[1,3,5,7],[2,4,6,8]])
print(dd)
dd[:,2]=[6,5]
print(dd)

[[1 3 5 7]
 [2 4 6 8]]
[[1 3 6 7]
 [2 4 5 8]]


In [32]:
#3d array
ddd=np.array([[[1,3,5,7],[2,4,6,8]],[[7,5,3,1],[8,6,4,2]]])
print(ddd)

[[[1 3 5 7]
  [2 4 6 8]]

 [[7 5 3 1]
  [8 6 4 2]]]


In [33]:
ddd[1,0,1]

5

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
#creating a array with other numbers
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [35]:
#creating a array of similar size as a array
np.full_like(dd,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [16]:
#creating a array with random numbers
np.random.rand(3,2)

array([[0.87433556, 0.30939782],
       [0.96918947, 0.11994847],
       [0.67584738, 0.59379508]])

In [36]:
#creating a array with random numbers
n1=np.random.randint(10,size=(3,3))
print(n1)
print()
n2=np.random.randint(5,10,size=(3,3))
print(n2)

[[0 5 9]
 [8 8 2]
 [1 9 0]]

[[7 5 8]
 [7 9 8]
 [9 7 7]]


In [18]:
#creating identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
#repeating an array
n=np.array([[1,2,3,4]])
n4=np.repeat(n,3,axis=0)
print(n4)
print()
n=np.array([[1,2,3,4]])
n4=np.repeat(n,3,axis=1)
print(n4)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

[[1 1 1 2 2 2 3 3 3 4 4 4]]


In [20]:
out= np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
#print(z)
out[1:4,1:4]=z
print(out)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
a= np.array([1,2,3])
b=a.copy()
print(b)
print()
b[0]=10
print(b)
print(a)

[1 2 3]

[10  2  3]
[1 2 3]


In [22]:
#array mathematics
a= np.array([1,2,3,4])

summ= a+2
multiplication = a*2
power= a**2
sinValue= np.sin(a)
print()
print(a)
print(summ)
print(power)
print(sinValue)


[1 2 3 4]
[3 4 5 6]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [39]:
a= np.array([[1,2,3],[4,5,6]])
print(a)
print()
np.min(a)
#print()
np.min(a,axis=1)


[[1 2 3]
 [4 5 6]]



array([1, 4])

In [24]:
#reshape
a=  np.array([[1,2,3],[4,5,6]])
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
#Vertical stacking
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a= np.vstack([a1,a2])
print(a)

[[1 2 3]
 [4 5 6]]


In [41]:
#horizontal stacking
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a= np.hstack([a1,a2])
print(a)

[1 2 3 4 5 6]


In [42]:
#eye function
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [43]:
#arrange function
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [44]:
#transpose
a=np.random.randint(0, 10, (4,4))
print(a)
print()
print()
print(a.T)

[[1 8 4 3]
 [1 4 2 7]
 [0 7 4 9]
 [6 3 0 1]]


[[1 1 0 6]
 [8 4 7 3]
 [4 2 4 0]
 [3 7 9 1]]


In [53]:
x = np.arange(8)
print(x)
print()
np.split(x, [3, 5, 6, 8])

[0 1 2 3 4 5 6 7]



[array([0, 1, 2]),
 array([3, 4]),
 array([5]),
 array([6, 7]),
 array([], dtype=int64)]

In [1]:
import pandas as pd
a=pd.read_csv("https://www.cs.helsinki.fi/u/jttoivon/dap/data/fmi/kumpula-weather-2017.csv")['Air temperature (degC)'].values

print(a)

[  0.6  -3.9  -6.5 -12.8 -17.8 -17.8  -3.8  -0.5   0.5   1.7  -1.6  -2.8
   1.1   0.8  -2.8  -4.2  -3.5   1.1   1.6  -0.6  -1.8   1.    0.1  -2.2
  -3.8   1.9   1.6   0.8   0.6   1.    0.2  -0.6  -0.8  -0.2   0.4  -2.5
  -7.3 -12.1  -8.8 -10.1  -8.3  -5.4  -2.7   1.5   4.4   0.    0.5   1.5
   1.9   2.2   0.4  -2.5  -4.6  -0.7  -5.3  -5.6  -2.   -2.3   2.1   1.5
   1.5   0.9  -1.8  -4.2  -4.2  -2.9   0.2   1.2   1.4   2.2  -0.9   0.6
   0.6   3.8   3.4   2.    1.6   0.6   0.2   1.6   2.3   2.5   0.5   1.9
   4.8   6.6   2.4   0.4  -0.4   0.2   1.5   4.3   3.    3.8   3.3   4.7
   4.1   3.3   3.7   6.    4.3   1.8   1.2  -0.5  -1.4  -1.7   0.6   0.3
   1.2   2.5   5.7   3.1   2.9   3.6   2.8   3.2   4.4   4.1   2.3   2.2
   7.6   9.4   9.2   6.7  10.1  11.1   6.1   4.4   1.5   1.5   2.9   5.1
   7.5   9.8   9.    7.3   9.4  11.2  16.1  16.9  14.7  14.6  13.3  12.4
  14.1  14.1   9.6  13.2  14.1   9.6  10.8   6.5   6.2  10.    9.9  10.4
  14.5  16.4  12.3  14.   16.3  16.8  12.6  12.6  1

In [2]:
#printing the boolean
c=a<0
print(c)

[False  True  True  True  True  True  True  True False False  True  True
 False False  True  True  True False False  True  True False False  True
  True False False False False False False  True  True  True False  True
  True  True  True  True  True  True  True False False False False False
 False False False  True  True  True  True  True  True  True False False
 False False  True  True  True  True False False False False  True False
 False False False False False False False False False False False False
 False False False False  True False False False False False False False
 False False False False False False False  True  True  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False Fa

In [7]:
#printing the actual values
c=a<0
print(a[c])

[ -3.9  -6.5 -12.8 -17.8 -17.8  -3.8  -0.5  -1.6  -2.8  -2.8  -4.2  -3.5
  -0.6  -1.8  -2.2  -3.8  -0.6  -0.8  -0.2  -2.5  -7.3 -12.1  -8.8 -10.1
  -8.3  -5.4  -2.7  -2.5  -4.6  -0.7  -5.3  -5.6  -2.   -2.3  -1.8  -4.2
  -4.2  -2.9  -0.9  -0.4  -0.5  -1.4  -1.7  -0.3  -0.4  -1.2  -0.8  -0.1
  -0.3]


In [10]:
# Temperature is greater than 0 and less that 10
np.sum((0 < a) & (a < 10))     

185

In [23]:
z2=a>=0.0
print(a[z2])

[ 0.6  0.5  1.7  1.1  0.8  1.1  1.6  1.   0.1  1.9  1.6  0.8  0.6  1.
  0.2  0.4  1.5  4.4  0.   0.5  1.5  1.9  2.2  0.4  2.1  1.5  1.5  0.9
  0.2  1.2  1.4  2.2  0.6  0.6  3.8  3.4  2.   1.6  0.6  0.2  1.6  2.3
  2.5  0.5  1.9  4.8  6.6  2.4  0.4  0.2  1.5  4.3  3.   3.8  3.3  4.7
  4.1  3.3  3.7  6.   4.3  1.8  1.2  0.6  0.3  1.2  2.5  5.7  3.1  2.9
  3.6  2.8  3.2  4.4  4.1  2.3  2.2  7.6  9.4  9.2  6.7 10.1 11.1  6.1
  4.4  1.5  1.5  2.9  5.1  7.5  9.8  9.   7.3  9.4 11.2 16.1 16.9 14.7
 14.6 13.3 12.4 14.1 14.1  9.6 13.2 14.1  9.6 10.8  6.5  6.2 10.   9.9
 10.4 14.5 16.4 12.3 14.  16.3 16.8 12.6 12.6 14.8 15.1 18.4 19.3 16.9
 17.8 12.7 12.4 12.2 10.8 12.9 14.  13.5 13.7 15.3 16.3 17.2 14.1 16.4
 14.5 14.1 14.  11.5 14.7 16.1 17.4 18.  16.8 16.8 14.7 15.3 16.7 18.
 15.4 15.  13.7 14.6 15.8 15.6 16.9 15.7 16.1 17.2 19.  19.1 17.8 18.3
 17.8 18.9 17.5 18.2 16.6 17.1 16.  15.2 17.2 18.3 18.7 18.1 19.6 17.4
 16.1 16.4 17.6 19.  18.  18.2 17.4 16.2 14.9 13.5 12.9 11.2 10.4 10.7
 12.  14

In [36]:
b=np.arange(16).reshape(4,4)
print(b)
row=np.array([0,2])
col=np.array([2,0])
print(b[row, col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[2 8]


In [38]:
row2=np.array([[0, 0], [2,2]])
col2=np.array([[1,3], [1,2]])
print(row2)
print(col2)
print(b[row2, col2])

[[0 0]
 [2 2]]
[[1 3]
 [1 2]]
[[ 1  3]
 [ 9 10]]
